const assetData = [
    [
        './../../../../assets/gallery/asuna/headCrush/asunaHeadCrush.mp4',
    ],
    [
        './../../../../assets/gallery/asuna/aSlowCrush/ASlowCrush.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page1.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page2.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page3.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page4.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page5.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page6.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page7.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page8.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page9.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page10.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page11.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page12.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page13.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page14.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page15.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page16.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page17.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page18.jpg',
        './../../../../assets/gallery/asuna/aSlowCrush/Page19FINAL.jpg',
    ],
    [
        './../../../../assets/gallery/asuna/barefoot/barefoot.mp4',
    ],
    [
        './../../../../assets/gallery/asuna/cityCrush/asunaCityCrush.mp4',
    ],
    [
        './../../../../assets/gallery/asuna/tease/asunaTease.mp4',
    ],
]

document.addEventListener("DOMContentLoaded", () => {
    asuna.loadGalleryContent(assetData);
});