const lami = new girl(
    {
        name: 'Lami',
        services: '52',
        shoe: '90$',
        barefoot: '150$',
        inshoe: '130$',
        butt: 'N/A',
        breast: '300$',
        hands: 'N/A',
        swallow: '400$',
        chewing: 'N/A',
        fWorship: '5$/min',
        fMassage: '3$/min',
        anitacids: '1000$',
        toenails: '10$',
        description: 'One of the newest girls here. She is kind and happy. She loves to be pampered but its also shy. Her favorite type of crush is barefoot as she loves the feeling of the tinies under her feet so if you are looking for a good foot crush you know where to find it! And remember to treat her gentle, she is so adorable!',
        quote: 'Hii! Im not very experienced with this but I want to improve so if you choose a foot crush from me Ill try my best to please you! I also do vore (only sallowing) if you like that but im not very good at it haha. I tried butt crush but its hard for me and I dont have enough strength for hand crush...',
        aboutHer: '',
        vores: '',
        crushes: '',
        height: '',
        weight: '',
        footSize: '',
    },
    '../../../assets/Logo.png',
    './../../../whoWeAre.html',
    [
        { text: 'Location', href: '#' },
        { text: 'About us', href: './../../../whoWeAre.html' },
        { text: 'Our girls', href: './../ourGirls.html' },
        { text: 'Gallery', href: '#' },
        { text: 'Work with us', href: '#' }
    ]
);
