const girl = {
    name: '',
    services: '',
    shoe: '',
    barefoot: '',
    inshoe: '',
    butt: '',
    breast: '',
    hands: '',
    swallow: '',
    chewing: '',
    fWorship: '',
    fMassage: '',
    anitacids: '',
    toenails: '',
    description: '',
    quote: '',
    vores: '',
    crushes: '',
    height: '',
    weight: '',
    footSize: '',
};