const mika = new girl(
    {
        name: 'Mika',
        services: '1045',
        shoe: '600$',
        barefoot: '500$',
        inshoe: '800$',
        butt: '1000$',
        breast: '1200$',
        hands: '1100$',
        swallow: '2000$',
        chewing: '1000$',
        fWorship: '10$/min',
        fMassage: '8$/min',
        anitacids: '50$',
        toenails: '45$',
        description: 'One of the new and most popular girls! Mika is a cute girl that honestly thinks men only exist to please girls in any way. She will end you with a smile in her face but she wont care about you even a bit! She is just doing this because it feels nice. She cares less about you than Iori!',
        quote: 'Heey! Im Mika. I love to feel guys explode under my feet or disolve in my stomach. I can do any service except breast crush because is not very fun, but I enjoy foot crush and vore the most. Oh! And I also love younger boys because they are cute and easier to crush so come as soon as you can here and let me end you like a good boy!',
        aboutHer: '',
        vores: '',
        crushes: '',
        height: '',
        weight: '',
        footSize: '',
    },
    '../../../assets/Logo.png',
    './../../../whoWeAre.html',
    [
        { text: 'Location', href: '#' },
        { text: 'About us', href: './../../../whoWeAre.html' },
        { text: 'Our girls', href: './../ourGirls.html' },
        { text: 'Gallery', href: '#' },
        { text: 'Work with us', href: '#' }
    ]
);
